AWSTemplateFormatVersion: '2010-09-09'
Description: Template to launch an Amazon EC2 instance.

Resources:
  MySecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow
      SecurityGroupIngress:
       - IpProtocol: TCP
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: TCP
         FromPort: 8080
         ToPort: 8080
         CidrIp: 0.0.0.0/0
      
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-01a00762f46d584a1
      InstanceType: c7i-flex.large
      KeyName: Linux-mumbai
      SecurityGroupIds: 
        - !Ref MySecurityGroup1
      Tags:
        - Key: Name
          Value: Ubuntu-Server-2 
    